# Generated by Django 5.0.3 on 2024-04-01 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored_todos', to='todo.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='todos_participated', to='todo.user'),
        ),
    ]
